exports.esami = {
    ecografia : [
        {nome : 'Addome superiore'},
        {nome : 'Addome inferiore'},
        {nome : 'Addome completo'},
        {nome : 'Addome completo con studio delle anse'},
        {nome : 'Reni e Surreni'},
        {nome : 'Grossi Vasi Addominali'},
        {nome : 'ECD arterie renali'},
        {nome : 'Mammella e linfonodi ascellari'},
        {nome : 'Collo'},
        {nome : 'Tiroide e Paratiroidi'},
        {nome : 'Ghiandole Salivari'},
        {nome : 'Stazioni linfonodali superficiali'},
        {nome : 'Osteo-articolare'},
        {nome : 'Muscolo-tendinea'},
        {nome : 'Cute e Sottocute'},
        {nome : 'Scrotale'},
    ],
    ECD :[
        {nome : 'Arti Superiori e Inferiori Arterioso e Venoso'},
        {nome : 'TSA'},
    ],
    RX:[
        {nome : 'Cranio'},
        {nome : 'Seni Paranasali'},
        {nome : 'Torace'},
        {nome : 'Emitorace per Coste'},
        {nome : 'Sterno e Clavicola'},
        {nome : 'Colonna Cervicale'},
        {nome : 'Colonna Dorsale'},
        {nome : 'Colonna Lombare'},
        {nome : 'Colonna Lombo-Sacrale'},
        {nome : 'Regione Sacro-Coccigea'},
        {nome : 'Bacino'},
        {nome : 'Anca'},
        {nome : 'Spalla'},
        {nome : 'Omero'},
        {nome : 'Gomito'},
        {nome : 'Avambraccio'},
        {nome : 'Polso'},
        {nome : 'Mano'},
        {nome : 'Femore'},
        {nome : 'Ginocchio'},
        {nome : 'Gamba'},
        {nome : 'Caviglia'},
        {nome : 'Piede'},
        {nome : 'Addome'},
        {nome : 'Reno-Vescicale'},
    ],
    'mammografia': [
        {nome : 'Digitale diretta 2D'},
        {nome : 'Digitale diretta 3D (Tomosintesi)'},

    ]
}

